### PR TITLE
Automatic REL Decompression Support (#6)

### PR DESCRIPTION
**Pull request by JohnP55**
ouptut

### CODE REVIEW

**Comment by SeekyCt** [comment]
I think we should add a comment at the top of lzss3.py with a copy of the [license](https://github.com/magical/nlzss/blob/master/LICENSE) and a link to the original repo.

Probably also worth figuring out why your PRs are all including all the commits from your previous ones, since this time the changes are actually showing up in the diff too. I think you might just need to use `sync fork` on the github page for your fork?

**Comment by JohnP55** [comment]
Yea idk why they all showed up in the diff too, I'll try to figure this out

**Comment by ribbanya** [comment]
Try this:
```sh
git rebase --onto 59ab173 58a7460 9df05e6
```

Reference: https://stackoverflow.com/a/29916361/5880994

**Comment by SeekyCt** [comment]
Looks good, thanks

**Pull request merged**
